services:
  php:
    build: .
    container_name: turnos-php
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: turnos-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: turnos-db
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: turnos_app
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./sql/seeds.sql:/docker-entrypoint-initdb.d/02-seeds.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-udev", "-pdev1234"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: